//! forge — the tool factory's scaffolding + Homebrew-formula generator.
//!
//! Source of truth is each tool's `tools/<name>/tool.json`. forge derives the
//! Homebrew formula from it (CI calls `forge formula` on release with the
//! built asset's URL + sha256) and lints the manifest against the rules
//! `brew audit --strict` enforces — so a bad manifest is caught at commit time,
//! not after a wasted build/release.
//!
//! Kept deliberately small. `new`/`dev`/`release` conveniences are layered on
//! later; the load-bearing pieces (generate the formula, lint the manifest) come
//! first.

use std::path::{Path, PathBuf};

use anyhow::{Context, Result, bail};
use clap::{Parser, Subcommand};
use serde::Deserialize;

#[derive(Parser)]
#[command(
    name = "forge",
    version,
    about = "Scaffolding + formula generator for the tap"
)]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Subcommand)]
enum Command {
    /// Render Formula/<tool>.rb from tool.json + a released asset (CI uses this).
    Formula {
        /// Tool name (a directory under tools/).
        name: String,
        /// Release version, e.g. 0.1.0 (from the git tag).
        #[arg(long)]
        version: String,
        /// Download URL of the darwin-arm64 release tarball.
        #[arg(long)]
        url: String,
        /// SHA-256 of that tarball.
        #[arg(long)]
        sha256: String,
        /// Write to this path instead of Formula/<tool>.rb.
        #[arg(long)]
        out: Option<PathBuf>,
    },
    /// Validate tool.json against the rules `brew audit --strict` enforces.
    Lint {
        /// Tool name (a directory under tools/).
        name: String,
    },
}

#[derive(Deserialize)]
struct Manifest {
    name: String,
    lang: String,
    bin: String,
    desc: String,
    homepage: String,
    license: String,
    #[allow(dead_code)]
    #[serde(default)]
    targets: Vec<String>,
    test: String,
}

fn load_manifest(name: &str) -> Result<Manifest> {
    let path = Path::new("tools").join(name).join("tool.json");
    let raw =
        std::fs::read_to_string(&path).with_context(|| format!("reading {}", path.display()))?;
    let m: Manifest =
        serde_json::from_str(&raw).with_context(|| format!("parsing {}", path.display()))?;
    Ok(m)
}

/// `imap-extract` -> `ImapExtract` (the Ruby class name brew expects).
fn class_name(name: &str) -> String {
    name.split('-')
        .filter(|s| !s.is_empty())
        .map(|seg| {
            let mut c = seg.chars();
            match c.next() {
                Some(first) => first.to_ascii_uppercase().to_string() + c.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

fn render_formula(m: &Manifest, version: &str, url: &str, sha256: &str) -> String {
    let class = class_name(&m.name);
    format!(
        "# Generated by forge from tools/{name}/tool.json — do not edit by hand.\n\
         # Re-render via `forge formula {name}` (CI does this on each release).\n\
         class {class} < Formula\n\
         \x20 desc \"{desc}\"\n\
         \x20 homepage \"{homepage}\"\n\
         \x20 version \"{version}\"\n\
         \x20 url \"{url}\"\n\
         \x20 sha256 \"{sha256}\"\n\
         \x20 license \"{license}\"\n\
         \n\
         \x20 def install\n\
         \x20\x20\x20 bin.install \"{bin}\"\n\
         \x20 end\n\
         \n\
         \x20 test do\n\
         \x20\x20\x20 system bin/\"{bin}\", \"{test}\"\n\
         \x20 end\n\
         end\n",
        name = m.name,
        class = class,
        desc = m.desc,
        homepage = m.homepage,
        version = version,
        url = url,
        sha256 = sha256,
        license = m.license,
        bin = m.bin,
        test = m.test,
    )
}

/// Lint the manifest against the rules `brew audit --strict` enforces, plus our
/// own license gate. Returns the list of problems (empty = clean).
fn lint(m: &Manifest) -> Vec<String> {
    let mut errs = Vec::new();

    // Slug: lowercase, starts alpha, no double hyphen, maps to a CamelCase class.
    let slug_ok = !m.name.is_empty()
        && m.name
            .chars()
            .next()
            .is_some_and(|c| c.is_ascii_lowercase())
        && m.name
            .chars()
            .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-')
        && !m.name.contains("--");
    if !slug_ok {
        errs.push(format!(
            "name `{}` must match ^[a-z][a-z0-9-]*$ with no double hyphen",
            m.name
        ));
    }

    if !matches!(m.lang.as_str(), "rust" | "bun") {
        errs.push(format!("lang `{}` must be \"rust\" or \"bun\"", m.lang));
    }

    // desc rules (brew audit --strict).
    let d = m.desc.trim();
    if d.is_empty() {
        errs.push("desc is empty".into());
    }
    let first = d
        .split_whitespace()
        .next()
        .unwrap_or("")
        .to_ascii_lowercase();
    if matches!(first.as_str(), "a" | "an" | "the") {
        errs.push("desc must not start with an article (a/an/the)".into());
    }
    if d.to_ascii_lowercase()
        .contains(&m.name.to_ascii_lowercase())
    {
        errs.push("desc must not contain the formula name (brew prepends it)".into());
    }
    if d.ends_with('.') {
        errs.push("desc must not end with a period".into());
    }
    // brew renders "<name>: <desc>" and caps the whole thing near 80 chars.
    if m.name.len() + 2 + d.len() > 80 {
        errs.push(format!(
            "desc too long: \"<name>: <desc>\" is {} chars (max 80)",
            m.name.len() + 2 + d.len()
        ));
    }

    if !m.homepage.starts_with("https://") {
        errs.push("homepage must be an https:// URL".into());
    }

    // License gate: require a license, reject copyleft (we ship permissive binaries).
    let lic = m.license.to_ascii_uppercase();
    if m.license.trim().is_empty() {
        errs.push("license is required (SPDX id)".into());
    } else if lic.contains("GPL") || lic.contains("AGPL") {
        errs.push(format!(
            "license `{}` is copyleft — the tap ships permissive binaries only",
            m.license
        ));
    }

    if m.test.trim().is_empty() {
        errs.push("test is empty (name a deterministic subcommand, e.g. \"selftest\")".into());
    }

    errs
}

fn main() -> Result<()> {
    let cli = Cli::parse();
    match cli.command {
        Command::Formula {
            name,
            version,
            url,
            sha256,
            out,
        } => {
            let m = load_manifest(&name)?;
            let problems = lint(&m);
            if !problems.is_empty() {
                for p in &problems {
                    eprintln!("forge: lint: {p}");
                }
                bail!(
                    "{} has {} lint problem(s); fix tool.json first",
                    name,
                    problems.len()
                );
            }
            let rb = render_formula(&m, &version, &url, &sha256);
            let out = out.unwrap_or_else(|| Path::new("Formula").join(format!("{name}.rb")));
            if let Some(parent) = out.parent() {
                std::fs::create_dir_all(parent)?;
            }
            std::fs::write(&out, rb)?;
            println!("forge: wrote {}", out.display());
        }
        Command::Lint { name } => {
            let m = load_manifest(&name)?;
            let problems = lint(&m);
            if problems.is_empty() {
                println!("forge: {name} tool.json OK");
            } else {
                for p in &problems {
                    eprintln!("forge: lint: {p}");
                }
                bail!("{} has {} lint problem(s)", name, problems.len());
            }
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn manifest(desc: &str, license: &str) -> Manifest {
        Manifest {
            name: "imap-extract".into(),
            lang: "rust".into(),
            bin: "imap-extract".into(),
            desc: desc.into(),
            homepage: "https://github.com/orlenko/homebrew-tap".into(),
            license: license.into(),
            targets: vec![],
            test: "selftest".into(),
        }
    }

    #[test]
    fn class_name_camelcases() {
        assert_eq!(class_name("imap-extract"), "ImapExtract");
        assert_eq!(class_name("forge"), "Forge");
        assert_eq!(class_name("a-b-c"), "ABC");
    }

    #[test]
    fn lint_accepts_a_good_manifest() {
        let m = manifest(
            "Watch an IMAP folder and export new mail as Markdown",
            "MIT",
        );
        assert!(lint(&m).is_empty(), "{:?}", lint(&m));
    }

    #[test]
    fn lint_rejects_copyleft() {
        let errs = lint(&manifest("Watch mail and export as Markdown", "GPL-3.0"));
        assert!(errs.iter().any(|e| e.contains("copyleft")), "{errs:?}");
    }

    #[test]
    fn lint_rejects_article_name_and_period() {
        let errs = lint(&manifest("The imap-extract tool does stuff.", "MIT"));
        assert!(errs.iter().any(|e| e.contains("article")), "{errs:?}");
        assert!(errs.iter().any(|e| e.contains("formula name")), "{errs:?}");
        assert!(errs.iter().any(|e| e.contains("period")), "{errs:?}");
    }

    #[test]
    fn render_is_valid_shape() {
        let rb = render_formula(
            &manifest("Watch mail and export as Markdown", "MIT"),
            "0.1.0",
            "https://x/y.tar.gz",
            "abc123",
        );
        assert!(rb.contains("class ImapExtract < Formula"));
        assert!(rb.contains("sha256 \"abc123\""));
        assert!(rb.contains("system bin/\"imap-extract\", \"selftest\""));
    }
}
