# Generated by forge from tools/gootodoo/tool.json — do not edit by hand.
# Re-render via `forge formula gootodoo` (CI does this on each release).
class Gootodoo < Formula
  desc "Idempotently write Google Tasks and Calendar from NDJSON intents"
  homepage "https://github.com/orlenko/homebrew-tap"
  url "https://github.com/orlenko/homebrew-tap/releases/download/gootodoo-v0.2.0/gootodoo-aarch64-apple-darwin.tar.gz"
  sha256 "040c5959d3d9a20b8a335bf632d651cabf5f823696d615409f2e798464197489"
  license "MIT"

  def install
    bin.install "gootodoo"
  end

  test do
    system bin/"gootodoo", "selftest"
  end
end
