# Generated by forge from tools/gpush/tool.json — do not edit by hand.
# Re-render via `forge formula gpush` (CI does this on each release).
class Gpush < Formula
  desc "Idempotently write Google Tasks and Calendar from NDJSON intents"
  homepage "https://github.com/orlenko/homebrew-tap"
  url "https://github.com/orlenko/homebrew-tap/releases/download/gpush-v0.1.0/gpush-aarch64-apple-darwin.tar.gz"
  sha256 "2da923fee4ce001a3e002d55e2f73727c0d8818c6c4ff489d158fd08fb4e0712"
  license "MIT"

  def install
    bin.install "gpush"
  end

  test do
    system bin/"gpush", "selftest"
  end
end
