# Generated by forge from tools/imap-extract/tool.json — do not edit by hand.
# Re-render via `forge formula imap-extract` (CI does this on each release).
class ImapExtract < Formula
  desc "Watch an IMAP folder over IDLE and export new mail as Markdown"
  homepage "https://github.com/orlenko/homebrew-tap"
  url "https://github.com/orlenko/homebrew-tap/releases/download/imap-extract-v0.1.2/imap-extract-aarch64-apple-darwin.tar.gz"
  sha256 "cce9bbcdf7fb99c02f2057cf9b1ee07632867134bdb3aee2a55a299c892e5b50"
  license "MIT"

  def install
    bin.install "imap-extract"
  end

  test do
    system bin/"imap-extract", "selftest"
  end
end
