# Generated by forge from tools/imap-extract/tool.json — do not edit by hand.
# Re-render via `forge formula imap-extract` (CI does this on each release).
class ImapExtract < Formula
  desc "Watch an IMAP folder over IDLE and export new mail as Markdown"
  homepage "https://github.com/orlenko/homebrew-tap"
  url "https://github.com/orlenko/homebrew-tap/releases/download/imap-extract-v0.1.1/imap-extract-aarch64-apple-darwin.tar.gz"
  sha256 "e28c5839f289685edeae65cc0262ebd757c7e5306ff6cabf158ff2b5049389f8"
  license "MIT"

  def install
    bin.install "imap-extract"
  end

  test do
    system bin/"imap-extract", "selftest"
  end
end
