# Generated by forge from tools/imap-extract/tool.json — do not edit by hand.
# Re-render via `forge formula imap-extract` (CI does this on each release).
class ImapExtract < Formula
  desc "Watch an IMAP folder over IDLE and export new mail as Markdown"
  homepage "https://github.com/orlenko/homebrew-tap"
  version "0.1.0"
  url "https://github.com/orlenko/homebrew-tap/releases/download/imap-extract-v0.1.0/imap-extract-aarch64-apple-darwin.tar.gz"
  sha256 "c6ce184c44905f190110e52ad759b67e888bf789cc05960836b0904e4a25d476"
  license "MIT"

  def install
    bin.install "imap-extract"
  end

  test do
    system bin/"imap-extract", "selftest"
  end
end
