# Generated by forge from tools/osavul-codex/tool.json — do not edit by hand.
# Re-render via `forge formula osavul-codex` (CI does this on each release).
class OsavulCodex < Formula
  desc "Run safe-codex with the osavul spool granted"
  homepage "https://github.com/orlenko/homebrew-tap"
  url "https://github.com/orlenko/homebrew-tap/releases/download/osavul-codex-v0.1.0/osavul-codex-aarch64-apple-darwin.tar.gz"
  sha256 "fe00bcfc05f2f02eaec435c28145c79d3e2530d935e607cc51603a8cdf208369"
  license "MIT"

  def install
    bin.install "osavul-codex"
  end

  test do
    system bin/"osavul-codex", "selftest"
  end
end
