# Generated by forge from tools/osavul-claude/tool.json — do not edit by hand.
# Re-render via `forge formula osavul-claude` (CI does this on each release).
class OsavulClaude < Formula
  desc "Run safe-claude with the osavul spool granted"
  homepage "https://github.com/orlenko/homebrew-tap"
  url "https://github.com/orlenko/homebrew-tap/releases/download/osavul-claude-v0.1.0/osavul-claude-aarch64-apple-darwin.tar.gz"
  sha256 "d287112292710fbb4509c525795a6e2fbc722e2e8e604c55d8237eeac18d4533"
  license "MIT"

  def install
    bin.install "osavul-claude"
  end

  test do
    system bin/"osavul-claude", "selftest"
  end
end
