# Generated by forge from tools/spaceman/tool.json — do not edit by hand.
# Re-render via `forge formula spaceman` (CI does this on each release).
class Spaceman < Formula
  desc "Delete stale, regenerable build directories from idle git checkouts"
  homepage "https://github.com/orlenko/homebrew-tap"
  url "https://github.com/orlenko/homebrew-tap/releases/download/spaceman-v0.1.0/spaceman-aarch64-apple-darwin.tar.gz"
  sha256 "49fab5e2d50ca9077e96538d14c5edabe7a09f4036c01ce68d62753881429e11"
  license "MIT"

  def install
    bin.install "spaceman"
  end

  test do
    system bin/"spaceman", "selftest"
  end
end
