# Generated by forge from tools/spaceman/tool.json — do not edit by hand.
# Re-render via `forge formula spaceman` (CI does this on each release).
class Spaceman < Formula
  desc "Clean up idle build dirs, stale Docker objects and old browser caches"
  homepage "https://github.com/orlenko/homebrew-tap"
  url "https://github.com/orlenko/homebrew-tap/releases/download/spaceman-v0.2.0/spaceman-aarch64-apple-darwin.tar.gz"
  sha256 "57c0348c94e5628bb5cd697619f46cc34464786122a2b14fe86b87bd14bb49c9"
  license "MIT"

  depends_on arch: :arm64
  depends_on :macos

  def install
    bin.install "spaceman"
  end

  test do
    system bin/"spaceman", "selftest"
  end
end
